### ISSUE TITLE
Notifications not sent to firebase?

### ISSUE THREAD

**Issue by brknkfr** [chteuchteu/Munin-for-Android-GCM-Proxy#2] opened 2021-03-25 07:09 UTC
Thank you for updating the GCM proxy.

I tried to install my own instance, unfortunately without luck. Steps I did to install my own instance:

1. I created a firebase project to get a "cloud messaging server key".
2. I installed Munin-for-Android-GCM-Proxy (with specifying the cloud messaging server key in GCM_API_KEY) with the deploy.sh script.
3. my-own-instance.tld/ping works (pongs back)
4. I changed the GCM_PROXY_URL and GCM_PROXY_TEST_URL in const.py on Munin-for-Android-GCM-Trigger and initated a `./main.py --test`
5. Nothing happens ... (No notification on devices.)

I don't know if the message is delivered correctly to GCM or where the problem is.

How can I debug the proxy? What logs are important? Where could be a possible problem? Thank you for any hints.

**Comment by brknkfr** [comment] 2021-03-25 08:06
When I try to send a notification via curl with given GCM_API_KEY, I get an error like `{"multicast_id":1098288334408535480,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"MismatchSenderId"}]}`. Could it be, that GCM proxy is not yet working with "new" server keys and on the main proxy, you still use an "old" server key? (Just a thougth)

**Comment by quentin-st** [comment] 2024-11-16 17:59
Hello @brknkfr ! Thanks for this issue. The project hasn't been updated to match Firebase's recent breaking changes - I'm looking into it, I'm taking this opportunity to modernize the project (Symfony migration, adding tests, ...)
I'll keep you in touch!

**Comment by quentin-st** [comment] 2024-11-17 17:20
@brknkfr Sorry about the (long) delay, the issue is now fixed! I was able to trigger a notification on my device through https://gcm-proxy.munin-for-android.com/trigger/declareAlert. Please let me know if everything works fine on your side.

**Closed as completed by quentin-st** 2024-11-17 17:20 UTC
